### ISSUE TITLE
USER STORY: Answering anonymously 

### ISSUE THREAD

**Issue by Eugene-Gwebu** [Eugene-Gwebu/My-First-Agile-Project-#2]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**.

## Acceptance Criteria: 

* The option should be provided as a checkbox.
* The checkbox should be "checked" automatically.  

### Tasks: 

- [ ] Task 1: Update the poll design to include the username.
- [ ] Task 2: Update the controller function.
- [ ] Task 3: Test functionality.
